# Comparing Performance of TGradAMI vs. TGrad (for EVI and Rainfall data).

In [1]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import from local directory
import sys
sys.path.insert(0, '../src')
from TemporalGP.TGP.tgrad_ami import TGradAMI
from TemporalGP.TGP.t_graank import TGrad

Configure TGradAMI algorithm hyperparameters.

In [2]:
# Hyperparameters

# f_path = "../datasets/air_quality1k.csv"
# f_path = "../datasets/air_quality25.csv"

f_path_evi = "../datasets/ke_evi_data_2k.csv"
f_path_rain = "../datasets/ke_rain_data_2k.csv"

eq = False
min_sup = 0.5
tgt_col = 1
tgt_cols = [1, 2, 3, 4]
min_rep = 0.75
mi_err_margin = 0.0001
eval_mode = True
clustering_method = False

Visualize the top 5 rows of the dataset.

In [3]:
rain_data = pd.read_csv(f_path_rain)
evi_data = pd.read_csv(f_path_evi)


print(rain_data.head())
print("\n")
print(evi_data.head())

  Date (Jul-Sep)   NRB (mm)   KAK (mm)   MAK (mm)   WAJ (mm)
0        07-2000   22.01000   526.8000      18.45  12.219990
1        07-2001   57.55001   539.0801       0.90  13.440000
2        07-2002   45.17000   349.2700      20.47  15.320000
3        07-2003   77.08001   660.0199       2.27   8.940001
4        07-2004   16.48000   424.6999       0.71   4.819999


  Date (Jul-Sep)   NRB (EVI)   KAK (EVI)   MAK (EVI)   WAJ (EVI)
0        07-2000    0.094866    0.401556    0.160511    0.120766
1        07-2001    0.236884    0.417010    0.183184    0.152754
2        07-2002    0.243191    0.370047    0.206061    0.109228
3        07-2003    0.202896    0.423199    0.159602    0.109228
4        07-2004    0.119559    0.378931    0.178707    0.099040

Initialize TGrad and TGradAMI algorithms by creating objects for different target columns.

In [4]:
rain_tgrads_ami = []
evi_tgrads_ami = []
for t_col in tgt_cols:
    t_grad_rain = TGradAMI(f_path_rain, min_sup, eq, target_col=t_col, min_rep=min_rep, min_error=mi_err_margin)
    t_grad_evi = TGradAMI(f_path_evi, min_sup, eq, target_col=t_col, min_rep=min_rep, min_error=mi_err_margin)

    rain_tgrads_ami.append(t_grad_rain)
    evi_tgrads_ami.append(t_grad_evi)


rain_tgrads = []
evi_tgrads = []
for t_col in tgt_cols:
    t_grad_rain = TGrad(f_path_rain, min_sup, eq, target_col=t_col, min_rep=min_rep)
    t_grad_evi = TGrad(f_path_evi, min_sup, eq, target_col=t_col, min_rep=min_rep)

    rain_tgrads.append(t_grad_rain)
    evi_tgrads.append(t_grad_evi)

Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok
Dataset Ok

Run the algorithm for mining FTGPs (Fuzzy Temporal Gradual Patterns) in evaluation mode. The algorithm returns a number of results in a dict format.

In [5]:
# rain_tgrad_data = []
# evi_tgrad_data = []
for i, t_grad_rain in enumerate(rain_tgrads_ami):
    eval_dict_rain = t_grad_rain.discover_tgp(use_clustering=clustering_method, eval_mode=eval_mode)
    transform_steps = eval_dict_rain['Transformation Steps']
    eval_dict_evi = evi_tgrads_ami[i].discover_tgp(use_clustering=clustering_method, transformation_steps=transform_steps, eval_mode=eval_mode)

    # rain_tgrad_data.append(eval_dict_rain)
    # evi_tgrad_data.append(eval_dict_evi)

Algorithm: TGradAMI
Minimum Representation: 0.78
MI Minimum Error: 0.00
MI Error: 0.02
Target Column: 1
Run-time: 0.755314 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 3

Attributes:
0. Date (Jul-Sep)
1. NRB (mm)
2. KAK (mm)
3. MAK (mm)
4. WAJ (mm)

File: ../datasets/ke_rain_data_2k.csv

Pattern : Support
['1+', '(2-) +12.0 months'] :  0.542
['1+', '(3-) +5.0 years'] :  0.549
['1+', '(4-) +2.0 years'] :  0.621

Algorithm: TGradAMI
Minimum Representation: 0.75
MI Minimum Error: 0.00
MI Error: 0.00
Target Column: 1
Run-time: 0.710725 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 3

Attributes:
0. Date (Jul-Sep)
1. NRB (EVI)
2. KAK (EVI)
3. MAK (EVI)
4. WAJ (EVI)

File: ../datasets/ke_evi_data_2k.csv

Pattern : Support
['1+', '(2-) +12.0 months'] :  0.51
['1+', '(3-) +5.0 years'] :  0.523
['1+', '(4-) +2.0 years'] :  0.647

Algorithm: TGradAMI
Minimum Representation: 0.87
MI Minimum Error: 0.00
MI Error: 0.00
Target Column: 2
Run-time: 0.537036 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 2

Attributes:
0. Date (Jul-Sep)
1. NRB (mm)
2. KAK (mm)
3. MAK (mm)
4. WAJ (mm)

File: ../datasets/ke_rain_data_2k.csv

Pattern : Support
['2-', '(1+) +3.0 years'] :  0.553
['2+', '(3+) +3.0 years'] :  0.542

Algorithm: TGradAMI
Minimum Representation: 0.75
MI Minimum Error: 0.00
MI Error: 0.00
Target Column: 2
Run-time: 0.572129 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 3

Attributes:
0. Date (Jul-Sep)
1. NRB (EVI)
2. KAK (EVI)
3. MAK (EVI)
4. WAJ (EVI)

File: ../datasets/ke_evi_data_2k.csv

Pattern : Support
['2-', '(1+) +3.0 years'] :  0.632
['2+', '(3+) +3.0 years'] :  0.553
['2+', '(4-) +3.0 years'] :  0.526

Algorithm: TGradAMI
Minimum Representation: 0.83
MI Minimum Error: 0.00
MI Error: 0.01
Target Column: 3
Run-time: 0.573002 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 3

Attributes:
0. Date (Jul-Sep)
1. NRB (mm)
2. KAK (mm)
3. MAK (mm)
4. WAJ (mm)

File: ../datasets/ke_rain_data_2k.csv

Pattern : Support
['3-', '(1+) +4.0 years'] :  0.661
['3+', '(2+) +3.0 years'] :  0.591
['3+', '(4+) +2.0 years'] :  0.55

Algorithm: TGradAMI
Minimum Representation: 0.75
MI Minimum Error: 0.00
MI Error: 0.00
Target Column: 3
Run-time: 0.616888 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 3

Attributes:
0. Date (Jul-Sep)
1. NRB (EVI)
2. KAK (EVI)
3. MAK (EVI)
4. WAJ (EVI)

File: ../datasets/ke_evi_data_2k.csv

Pattern : Support
['3+', '(1+) +4.0 years'] :  0.632
['3-', '(2+) +3.0 years'] :  0.515
['3+', '(4+) +2.0 years'] :  0.684

Algorithm: TGradAMI
Minimum Representation: 0.87
MI Minimum Error: 0.00
MI Error: 0.01
Target Column: 4
Run-time: 0.832202 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 3

Attributes:
0. Date (Jul-Sep)
1. NRB (mm)
2. KAK (mm)
3. MAK (mm)
4. WAJ (mm)

File: ../datasets/ke_rain_data_2k.csv

Pattern : Support
['4-', '(1+) +3.0 years'] :  0.716
['4-', '(2+) +3.0 years'] :  0.558
['4-', '(3+) +2.0 years'] :  0.526

Algorithm: TGradAMI
Minimum Representation: 0.75
MI Minimum Error: 0.00
MI Error: 0.00
Target Column: 4
Run-time: 0.602498 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 3

Attributes:
0. Date (Jul-Sep)
1. NRB (EVI)
2. KAK (EVI)
3. MAK (EVI)
4. WAJ (EVI)

File: ../datasets/ke_evi_data_2k.csv

Pattern : Support
['4+', '(1+) +3.0 years'] :  0.526
['4-', '(2+) +3.0 years'] :  0.505
['4-', '(3+) +2.0 years'] :  0.526

In [6]:
for i in range(len(rain_tgrads)):
    rain_tgrads[i].discover_tgp()
    evi_tgrads[i].discover_tgp()

Algorithm: TGrad
Minimum Representation: 0.75
Target Column: 1
Run-time: 4.019592 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 18

Attributes:
0. Date (Jul-Sep)
1. NRB (mm)
2. KAK (mm)
3. MAK (mm)
4. WAJ (mm)

File: ../datasets/ke_rain_data_2k.csv

Pattern : Support
['1+', '(2-) +12.0 months'] :  0.524
['1+', '(3-) +12.0 months'] :  0.532
['1+', '(4-) +12.0 months'] :  0.623
['1+', '(2-) +2.0 years'] :  0.519
['1+', '(3-) +2.0 years'] :  0.576
['1+', '(4-) +2.0 years'] :  0.624
['1+', '(2-) +3.0 years'] :  0.505
['1+', '(3+) +3.0 years'] :  0.616
['1+', '(4-) +3.0 years'] :  0.542
['1+', '(2-) +4.0 years'] :  0.538
['1+', '(3+) +4.0 years'] :  0.556
['1+', '(4+) +4.0 years'] :  0.567
['1+', '(2-) +5.0 years'] :  0.516
['1+', '(3-) +5.0 years'] :  0.549
['1+', '(4+) +5.0 years'] :  0.732
['1+', '(2+) +6.0 years'] :  0.507
['1+', '(3-) +6.0 years'] :  0.522
['1+', '(4-) +6.0 years'] :  0.515

Algorithm: TGrad
Minimum Representation: 0.75
Target Column: 1
Run-time: 3.953874 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 17

Attributes:
0. Date (Jul-Sep)
1. NRB (EVI)
2. KAK (EVI)
3. MAK (EVI)
4. WAJ (EVI)

File: ../datasets/ke_evi_data_2k.csv

Pattern : Support
['1+', '(2-) +12.0 months'] :  0.537
['1+', '(3+) +12.0 months'] :  0.519
['1+', '(4-) +12.0 months'] :  0.563
['1+', '(2-) +2.0 years'] :  0.51
['1+', '(3-) +2.0 years'] :  0.533
['1+', '(4-) +2.0 years'] :  0.629
['1+', '(2-) +3.0 years'] :  0.595
['1+', '(3+) +3.0 years'] :  0.526
['1+', '(4-) +3.0 years'] :  0.7
['1+', '(2+) +4.0 years'] :  0.579
['1+', '(3+) +4.0 years'] :  0.515
['1+', '(4+) +4.0 years'] :  0.52
['1+', '(2+) +5.0 years'] :  0.549
['1+', '(3-) +5.0 years'] :  0.523
['1+', '(4+) +5.0 years'] :  0.575
['1+', '(3-) +6.0 years'] :  0.559
['1+', '(4-) +6.0 years'] :  0.522

Algorithm: TGrad
Minimum Representation: 0.75
Target Column: 2
Run-time: 3.593155 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 16

Attributes:
0. Date (Jul-Sep)
1. NRB (mm)
2. KAK (mm)
3. MAK (mm)
4. WAJ (mm)

File: ../datasets/ke_rain_data_2k.csv

Pattern : Support
['2-', '(1+) +12.0 months'] :  0.563
['2+', '(3-) +12.0 months'] :  0.567
['2+', '(4-) +12.0 months'] :  0.623
['2-', '(1+) +2.0 years'] :  0.61
['2+', '(3-) +2.0 years'] :  0.61
['2-', '(1+) +3.0 years'] :  0.553
['2+', '(3+) +3.0 years'] :  0.542
['2+', '(1+) +4.0 years'] :  0.573
['2+', '(3+) +4.0 years'] :  0.532
['2+', '(4-) +4.0 years'] :  0.532
['2+', '(1+) +5.0 years'] :  0.549
['2+', '(3-) +5.0 years'] :  0.503
['2+', '(4+) +5.0 years'] :  0.588
['2+', '(1+) +6.0 years'] :  0.566
['2+', '(3+) +6.0 years'] :  0.507
['2+', '(4+) +6.0 years'] :  0.544

Algorithm: TGrad
Minimum Representation: 0.75
Target Column: 2
Run-time: 3.672430 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 18

Attributes:
0. Date (Jul-Sep)
1. NRB (EVI)
2. KAK (EVI)
3. MAK (EVI)
4. WAJ (EVI)

File: ../datasets/ke_evi_data_2k.csv

Pattern : Support
['2+', '(1+) +12.0 months'] :  0.602
['2+', '(3+) +12.0 months'] :  0.623
['2+', '(4+) +12.0 months'] :  0.506
['2+', '(1+) +2.0 years'] :  0.538
['2+', '(3+) +2.0 years'] :  0.538
['2+', '(4-) +2.0 years'] :  0.567
['2-', '(1+) +3.0 years'] :  0.632
['2+', '(3+) +3.0 years'] :  0.553
['2+', '(4-) +3.0 years'] :  0.526
['2-', '(1+) +4.0 years'] :  0.614
['2+', '(3+) +4.0 years'] :  0.515
['2+', '(4+) +4.0 years'] :  0.532
['2-', '(1+) +5.0 years'] :  0.582
['2+', '(3-) +5.0 years'] :  0.556
['2+', '(4-) +5.0 years'] :  0.575
['2+', '(1+) +6.0 years'] :  0.544
['2+', '(3-) +6.0 years'] :  0.515
['2+', '(4+) +6.0 years'] :  0.743

Algorithm: TGrad
Minimum Representation: 0.75
Target Column: 3
Run-time: 3.694413 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 17

Attributes:
0. Date (Jul-Sep)
1. NRB (mm)
2. KAK (mm)
3. MAK (mm)
4. WAJ (mm)

File: ../datasets/ke_rain_data_2k.csv

Pattern : Support
['3+', '(1+) +12.0 months'] :  0.545
['3+', '(2+) +12.0 months'] :  0.532
['3+', '(4+) +12.0 months'] :  0.528
['3-', '(1+) +2.0 years'] :  0.505
['3+', '(2+) +2.0 years'] :  0.514
['3+', '(4+) +2.0 years'] :  0.557
['3+', '(1+) +3.0 years'] :  0.505
['3+', '(2+) +3.0 years'] :  0.589
['3+', '(4-) +3.0 years'] :  0.537
['3-', '(1+) +4.0 years'] :  0.661
['3+', '(2+) +4.0 years'] :  0.556
['3+', '(4-) +4.0 years'] :  0.526
['3+', '(2+) +5.0 years'] :  0.641
['3+', '(4+) +5.0 years'] :  0.503
['3+', '(1+) +6.0 years'] :  0.537
['3+', '(2+) +6.0 years'] :  0.647
['3+', '(4+) +6.0 years'] :  0.544

Algorithm: TGrad
Minimum Representation: 0.75
Target Column: 3
Run-time: 3.590688 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 18

Attributes:
0. Date (Jul-Sep)
1. NRB (EVI)
2. KAK (EVI)
3. MAK (EVI)
4. WAJ (EVI)

File: ../datasets/ke_evi_data_2k.csv

Pattern : Support
['3-', '(1+) +12.0 months'] :  0.506
['3-', '(2+) +12.0 months'] :  0.515
['3+', '(4+) +12.0 months'] :  0.515
['3-', '(1+) +2.0 years'] :  0.762
['3-', '(2+) +2.0 years'] :  0.614
['3+', '(4+) +2.0 years'] :  0.652
['3-', '(1+) +3.0 years'] :  0.616
['3+', '(2+) +3.0 years'] :  0.521
['3+', '(4+) +3.0 years'] :  0.563
['3+', '(1+) +4.0 years'] :  0.632
['3+', '(2+) +4.0 years'] :  0.509
['3+', '(4+) +4.0 years'] :  0.614
['3+', '(1+) +5.0 years'] :  0.595
['3+', '(2+) +5.0 years'] :  0.523
['3+', '(4+) +5.0 years'] :  0.719
['3+', '(1+) +6.0 years'] :  0.596
['3-', '(2+) +6.0 years'] :  0.522
['3+', '(4-) +6.0 years'] :  0.544

Algorithm: TGrad
Minimum Representation: 0.75
Target Column: 4
Run-time: 3.748415 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 19

Attributes:
0. Date (Jul-Sep)
1. NRB (mm)
2. KAK (mm)
3. MAK (mm)
4. WAJ (mm)

File: ../datasets/ke_rain_data_2k.csv

Pattern : Support
['4+', '(1+) +12.0 months'] :  0.749
['4+', '(2+) +12.0 months'] :  0.589
['4+', '(3+) +12.0 months'] :  0.511
['4+', '(2+) +12.0 months', '(1+) +12.0 months'] :  0.511
['4+', '(1+) +2.0 years'] :  0.562
['4+', '(2+) +2.0 years'] :  0.543
['4-', '(3+) +2.0 years'] :  0.505
['4-', '(1+) +3.0 years'] :  0.716
['4-', '(2+) +3.0 years'] :  0.558
['4-', '(3+) +3.0 years'] :  0.589
['4-', '(1+) +4.0 years'] :  0.667
['4+', '(2+) +4.0 years'] :  0.52
['4+', '(3+) +4.0 years'] :  0.515
['4+', '(1+) +5.0 years'] :  0.542
['4+', '(2+) +5.0 years'] :  0.549
['4+', '(3+) +5.0 years'] :  0.562
['4+', '(1+) +6.0 years'] :  0.596
['4-', '(2+) +6.0 years'] :  0.522
['4-', '(3+) +6.0 years'] :  0.603

Algorithm: TGrad
Minimum Representation: 0.75
Target Column: 4
Run-time: 3.435415 seconds
No. of (dataset) attributes: 5
No. of (dataset) objects: 23
Minimum support: 0.5
Number of patterns: 18

Attributes:
0. Date (Jul-Sep)
1. NRB (EVI)
2. KAK (EVI)
3. MAK (EVI)
4. WAJ (EVI)

File: ../datasets/ke_evi_data_2k.csv

Pattern : Support
['4+', '(1+) +12.0 months'] :  0.545
['4+', '(2+) +12.0 months'] :  0.511
['4-', '(3+) +12.0 months'] :  0.511
['4+', '(1+) +2.0 years'] :  0.605
['4-', '(2+) +2.0 years'] :  0.638
['4-', '(3+) +2.0 years'] :  0.51
['4+', '(1+) +3.0 years'] :  0.526
['4-', '(2+) +3.0 years'] :  0.505
['4-', '(3+) +3.0 years'] :  0.558
['4-', '(1+) +4.0 years'] :  0.503
['4-', '(2+) +4.0 years'] :  0.591
['4+', '(3+) +4.0 years'] :  0.602
['4+', '(1+) +5.0 years'] :  0.654
['4-', '(2+) +5.0 years'] :  0.542
['4+', '(3+) +5.0 years'] :  0.523
['4+', '(1+) +6.0 years'] :  0.529
['4-', '(2+) +6.0 years'] :  0.625
['4+', '(3+) +6.0 years'] :  0.654

* Tabulate the mined FTGPs with their corresponding parameters

## TGradAMI FTGPs

In [7]:
patterns = [t_grad_rain.display_patterns_as_df for t_grad_rain in rain_tgrads_ami]  # Collect all patterns into a list
res_rain_df = pd.concat(patterns, ignore_index=True)  # Combine them in one go
res_rain_df

,Pattern,Support,Density,Avg. Deviation from Diagonal,Rank Dispersion,Graph Connectivity,Singularity Score
0,"NRB (mm)+, (KAK (mm)-) +12.0 months",0.542,0.328,6.602,4.338,1,3.084
1,"NRB (mm)+, (MAK (mm)-) +5.0 years",0.549,0.332,5.917,3.668,1,3.386
2,"NRB (mm)+, (WAJ (mm)-) +2.0 years",0.621,0.375,6.063,4.018,1,3.139
3,"KAK (mm)-, (NRB (mm)+) +3.0 years",0.553,0.415,7.124,4.372,1,2.146
4,"KAK (mm)+, (MAK (mm)+) +3.0 years",0.542,0.407,7.068,4.712,1,2.403
5,"MAK (mm)-, (NRB (mm)+) +4.0 years",0.661,0.447,6.611,4.297,1,2.678
6,"MAK (mm)+, (KAK (mm)+) +3.0 years",0.591,0.399,7.059,4.387,1,3.277
7,"MAK (mm)+, (WAJ (mm)+) +2.0 years",0.55,0.372,6.904,4.245,1,3.028
8,"WAJ (mm)-, (NRB (mm)+) +3.0 years",0.716,0.538,6.904,4.449,1,2.152
9,"WAJ (mm)-, (KAK (mm)+) +3.0 years",0.558,0.419,6.755,4.609,1,2.641
10,"WAJ (mm)-, (MAK (mm)+) +2.0 years",0.526,0.395,6.91,4.895,1,2.634

In [8]:
patterns = [t_grad_evi.display_patterns_as_df for t_grad_evi in evi_tgrads_ami]  # Collect all patterns into a list
res_evi_df = pd.concat(patterns, ignore_index=True)  # Combine them in one go
res_evi_df

,Pattern,Support,Density,Avg. Deviation from Diagonal,Rank Dispersion,Graph Connectivity,Singularity Score
0,"NRB (EVI)+, (KAK (EVI)-) +12.0 months",0.51,0.308,6.244,4.114,1,3.628
1,"NRB (EVI)+, (MAK (EVI)-) +5.0 years",0.523,0.316,6.125,3.779,1,3.131
2,"NRB (EVI)+, (WAJ (EVI)-) +2.0 years",0.647,0.391,6.273,4.005,1,3.502
3,"KAK (EVI)-, (NRB (EVI)+) +3.0 years",0.632,0.474,6.858,4.361,1,3.032
4,"KAK (EVI)+, (MAK (EVI)+) +3.0 years",0.553,0.415,6.181,3.949,1,2.555
5,"KAK (EVI)+, (WAJ (EVI)-) +3.0 years",0.526,0.395,7.47,4.898,1,2.304
6,"MAK (EVI)+, (NRB (EVI)+) +4.0 years",0.632,0.427,6.972,4.543,1,2.636
7,"MAK (EVI)-, (KAK (EVI)+) +3.0 years",0.515,0.348,7.034,4.466,1,3.302
8,"MAK (EVI)+, (WAJ (EVI)+) +2.0 years",0.684,0.462,6.735,4.365,1,2.997
9,"WAJ (EVI)+, (NRB (EVI)+) +3.0 years",0.526,0.395,7.09,4.434,1,2.124
10,"WAJ (EVI)-, (KAK (EVI)+) +3.0 years",0.505,0.379,7.802,4.573,1,2.058
11,"WAJ (EVI)-, (MAK (EVI)+) +2.0 years",0.526,0.395,7.17,4.794,1,2.664

## TGrad FTGPs

In [9]:
patterns = [t_grad_rain.display_patterns_as_df for t_grad_rain in rain_tgrads]
res_rain_df2 = pd.concat(patterns, ignore_index=True)
res_rain_df2

,Pattern,Support,Density,Avg. Deviation from Diagonal,Rank Dispersion,Graph Connectivity,Singularity Score
0,"NRB (mm)+, (KAK (mm)-) +12.0 months",0.524,0.478,7.471,4.929,1,1.511
1,"NRB (mm)+, (MAK (mm)-) +12.0 months",0.532,0.486,7.382,4.804,1,2.434
2,"NRB (mm)+, (WAJ (mm)-) +12.0 months",0.623,0.569,8.076,5.313,1,1.52
3,"NRB (mm)+, (KAK (mm)-) +2.0 years",0.519,0.431,6.743,4.426,1,1.76
4,"NRB (mm)+, (MAK (mm)-) +2.0 years",0.576,0.478,6.802,4.749,1,1.916
...,...,...,...,...,...,...,...
65,"WAJ (mm)+, (KAK (mm)+) +5.0 years",0.549,0.332,6.238,4.216,1,2.648
66,"WAJ (mm)+, (MAK (mm)+) +5.0 years",0.562,0.34,6.36,4.441,1,3.498
67,"WAJ (mm)+, (NRB (mm)+) +6.0 years",0.596,0.32,6.123,3.967,1,2.919
68,"WAJ (mm)-, (KAK (mm)+) +6.0 years",0.522,0.281,6.155,4.265,1,3.319
69,"WAJ (mm)-, (MAK (mm)+) +6.0 years",0.603,0.324,6.061,3.974,1,3.309

In [10]:
patterns = [t_grad_evi.display_patterns_as_df for t_grad_evi in evi_tgrads]
res_evi_df2 = pd.concat(patterns, ignore_index=True)
res_evi_df2

,Pattern,Support,Density,Avg. Deviation from Diagonal,Rank Dispersion,Graph Connectivity,Singularity Score
0,"NRB (EVI)+, (KAK (EVI)-) +12.0 months",0.537,0.49,7.944,5.176,1,2.113
1,"NRB (EVI)+, (MAK (EVI)+) +12.0 months",0.519,0.474,7.667,5.134,1,2.165
2,"NRB (EVI)+, (WAJ (EVI)-) +12.0 months",0.563,0.514,8.315,5.245,1,1.357
3,"NRB (EVI)+, (KAK (EVI)-) +2.0 years",0.51,0.423,6.832,4.477,1,2.602
4,"NRB (EVI)+, (MAK (EVI)-) +2.0 years",0.533,0.443,8.259,5.252,1,2.582
...,...,...,...,...,...,...,...
66,"WAJ (EVI)-, (KAK (EVI)+) +5.0 years",0.542,0.328,6.783,4.116,1,3.65
67,"WAJ (EVI)+, (MAK (EVI)+) +5.0 years",0.523,0.316,6.312,4.241,1,2.856
68,"WAJ (EVI)+, (NRB (EVI)+) +6.0 years",0.529,0.285,6.431,3.847,1,3.003
69,"WAJ (EVI)-, (KAK (EVI)+) +6.0 years",0.625,0.336,6.118,3.74,1,3.362
70,"WAJ (EVI)+, (MAK (EVI)+) +6.0 years",0.654,0.352,6.18,4.134,1,3.632

## Compute recall, precision and F1 score of extracted FTGPs