# Performance of Gradual Warping Set Descriptors with DTW as the Baseline

In [27]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from dtw import dtw

## Import from local directory
import sys
sys.path.insert(0, '../src')
from TemporalGP.TGP.tgrad_ami import TGradAMI

Configure TGradAMI algorithm hyperparameters.

In [31]:
# Hyperparameters

# f_path = "../datasets/air_quality1k.csv"
# f_path = "../datasets/rain_temp2013-2015.csv"
# f_path = ".../datasets/ndvi/average_evi_mak.csv"
f_path = "../datasets/ke_rain_data_2k.csv"
# f_path = "../datasets/air_quality25.csv"
eq = False
min_sup = 0.5
tgt_col = 1
min_rep = 0.75
mi_err_margin = 0.0001
eval_mode = True
clustering_method = False

Visualize the top 5 rows of the dataset.

In [32]:
data = pd.read_csv(f_path)
data.head()
# data[[' NRB (mm)']]

  Date (Jul-Sep)   NRB (mm)   KAK (mm)   MAK (mm)   WAJ (mm)
0        07-2000   22.01000   526.8000      18.45  12.219990
1        07-2001   57.55001   539.0801       0.90  13.440000
2        07-2002   45.17000   349.2700      20.47  15.320000
3        07-2003   77.08001   660.0199       2.27   8.940001
4        07-2004   16.48000   424.6999       0.71   4.819999

Initialize TGradAMI algorithm by creating an object.

In [33]:
t_grad = TGradAMI(f_path, min_sup, eq, target_col=tgt_col, min_rep=min_rep, min_error=mi_err_margin)

Dataset Ok

Run the algorithm for mining FTGPs (Fuzzy Temporal Gradual Patterns) in evaluation mode. The algorithm returns a number of results in a dict format. The decomposed gradual pattern components are also returned. This GP component can be used in analyzing multiple timeseries.

In [34]:
eval_dict = t_grad.discover_tgp(use_clustering=clustering_method, eval_mode=eval_mode)
list_tgp = t_grad.gradual_patterns
trans_data = eval_dict['Transformed Data']
time_data = eval_dict['Time Data']

In [35]:
trans_df = pd.DataFrame(trans_data, columns=t_grad.titles)
# print(trans_data)
trans_df

    Date (Jul-Sep)  NRB (mm)  KAK (mm)   MAK (mm)  WAJ (mm)
0   Date (Jul-Sep)  NRB (mm)  KAK (mm)   MAK (mm)  WAJ (mm)
1          07-2000     22.01  539.0801   4.420001     13.44
2          07-2001  57.55001    349.27       6.75     15.32
3          07-2002     45.17  660.0199       1.51  8.940001
4          07-2003  77.08001  424.6999       1.29  4.819999
5          07-2004     16.48  327.3999  0.4299998     11.81
6          07-2005     31.76  567.6299       1.51     23.69
7          07-2006  47.21001  696.9501       7.46     13.65
8          07-2007      87.3  663.2001       1.68  9.049999
9          07-2008  79.17998    464.89       3.54      2.11
10         07-2009     14.09  574.6301   58.16999     10.32
11         07-2010     30.62  553.2299      10.74       5.8
12         07-2011  60.98001    231.75       3.71     23.69
13         07-2012     52.12  542.7199      23.16     18.96
14         07-2013  81.66998  513.9099       5.05  4.339999
15         07-2014  75.85999  455.1201       4.46     10.32
16         07-2015  44.38999     395.9      16.78     12.03
17         07-2016     21.96  633.7001       2.66     16.76
18         07-2017  66.84998    498.38   8.009999      12.3

In [36]:
res_df = t_grad.display_patterns_as_df
res_df

,Pattern,Support,Density,Avg. Deviation from Diagonal,Rank Dispersion,Graph Connectivity,Singularity Score
0,"NRB (mm)+, (KAK (mm)-) +12.0 months",0.542,0.328,6.602,4.338,1,3.084
1,"NRB (mm)+, (MAK (mm)-) +5.0 years",0.549,0.332,5.917,3.668,1,3.386
2,"NRB (mm)+, (WAJ (mm)-) +12.0 months",0.608,0.368,6.538,4.411,1,3.182

### We compute DTW computations

In [42]:
orig_data = t_grad.data
orig_data

array([['07-2000', '22.01', '526.8', '18.45', '12.21999'],
       ['07-2001', '57.55001', '539.0801', '0.9', '13.44'],
       ['07-2002', '45.17', '349.27', '20.47', '15.32'],
       ['07-2003', '77.08001', '660.0199', '2.27', '8.940001'],
       ['07-2004', '16.48', '424.6999', '0.7099997', '4.819999'],
       ['07-2005', '31.76', '327.3999', '4.420001', '11.81'],
       ['07-2006', '47.21001', '567.6299', '6.75', '23.69'],
       ['07-2007', '87.3', '696.9501', '1.51', '13.65'],
       ['07-2008', '79.17998', '663.2001', '1.29', '9.049999'],
       ['07-2009', '14.09', '464.89', '0.4299998', '2.11'],
       ['07-2010', '30.62', '574.6301', '1.51', '10.32'],
       ['07-2011', '60.98001', '553.2299', '7.46', '5.8'],
       ['07-2012', '52.12', '231.75', '1.68', '23.69'],
       ['07-2013', '81.66998', '542.7199', '3.54', '18.96'],
       ['07-2014', '75.85999', '513.9099', '58.16999', '4.339999'],
       ['07-2015', '44.38999', '455.1201', '10.74', '10.32'],
       ['07-2016', '21.96', '395.9', '3.71', '12.03'],
       ['07-2017', '66.84998', '633.7001', '23.16', '16.76'],
       ['07-2018', '47.03999', '498.38', '5.05', '12.3'],
       ['07-2019', '62.95', '600.3', '4.46', '9.79'],
       ['07-2020', '62.89999', '782.9', '16.78', '12.12'],
       ['07-2021', '34.18999', '684.9899', '2.66', '7.739999'],
       ['07-2022', '49.10001', '888.0496', '8.009999', '16.8']],
      dtype=object)

In [53]:
template = orig_data[1:, 1].astype(float)  # NRB
query_1 = orig_data[1:, 2].astype(float)  # KAK
query_2 = orig_data[1:, 3].astype(float)  # MAK
query_3 = orig_data[1:, 3].astype(float)  # WAJ

In [54]:
alignment_1 = dtw(query_1, template, keep_internals=True)
alignment_2 = dtw(query_2, template, keep_internals=True)
alignment_3 = dtw(query_3, template, keep_internals=True)

In [49]:
# Euclidean Distance
eucl_distance_1 = np.linalg.norm(template - query_1)
eucl_distance_2 = np.linalg.norm(template - query_2)
eucl_distance_3 = np.linalg.norm(template - query_3)

In [56]:
print("DTW Distance:")
print(f"NRB--KAK: {alignment_1.distance}")
print(f"NRB--MAK: {alignment_2.distance}")
print(f"NRB--WAJ: {alignment_3.distance}")

print("\nEuclidean Distance:")
print(f"NRB--KAK: {eucl_distance_1}")
print(f"NRB--MAK: {eucl_distance_2}")
print(f"NRB--WAJ: {eucl_distance_3}")

DTW Distance:
NRB--KAK: 14644.969250000002
NRB--MAK: 881.1198715000002
NRB--WAJ: 881.1198715000002

Euclidean Distance:
NRB--KAK: 2002.402314447756
NRB--MAK: 219.92637394210328
NRB--WAJ: 219.92637394210328

* We create a Pandas timeseries for each attribute of our transformed dataset.

In [ ]:
trans_time_arr = trans_data[1:, 0]
trans_data_arr = trans_data[1:, 1:]
col_count = trans_data_arr.shape[1]

trans_datetime_series = pd.to_datetime(trans_time_arr, format='%m-%Y')
trans_datetime_index = pd.DatetimeIndex(trans_datetime_series)

lst_trans_ts = []
lst_trans_titles = []
for col in range(col_count):
    trans_ts = pd.Series(trans_data_arr[:, col].astype(float), index=trans_datetime_index)
    lst_trans_titles.append(trans_data[0, col+1])
    lst_trans_ts.append(trans_ts)

* We plot transformed timeseries to visualize it

In [ ]:
plt.figure(figsize=(16,4))
for i in range(len(lst_trans_ts)):
    plt.plot(trans_datetime_index, lst_trans_ts[i], label=lst_trans_titles[i])
plt.legend()

## Multiple Timeseries Composition using FTGPs

We can use FTGPs to decompose the pairwise object pairs gradual items (GIs) or gradual patterns (GPs) (which are associated with specific attributes/timeseries) into a single scale *warping path* that will allow us to accurately measure the gradual similarity of different timeseries datasets.

* We can visualize the GIs or GPs as shown below.

In [ ]:
## SO4GP Method for getting GP Warping Sets
t_grad.fit_warpingset()
warping_set = t_grad.warping_set

In [ ]:
warping_set.keys()
#warping_set.items()

* We draw numerous plots to visualize the multiple timeseries decompositions using FTGPs. Timeseries data that have strong correlation will produce a decomposition graph with dense zigzag patterns. Those with weak correlation will produce a decomposition graph with sparse zigzag patterns.

In [ ]:
# Calculate the number of rows needed
num_plots = len(warping_set or {})
cols = 4
rows = math.ceil(num_plots / cols)

# Create subplots with the required number of rows and columns
fig, axes = plt.subplots(rows, cols, figsize=(20, rows * 5))
axes = axes.flatten()  # Flatten to make indexing easier

# Plot each component in its subplot
for idx, (key, val) in enumerate(warping_set.items()):
    axes[idx].plot([p[0] for p in val], [p[1] for p in val], '-', label=f"{key}")
    axes[idx].set_xlabel("GP 1 Index")
    axes[idx].set_ylabel("GP 2 Index")
    axes[idx].legend()
    axes[idx].set_title(f"GP Warping Path")

# Hide any extra subplots
for ax in axes[num_plots:]:
    ax.axis("off")

plt.tight_layout()
plt.show()